= Scripts for OpenShift Virtualization Operations

== Containerized ENV
While not required, this repository (along with helpful tooling such as `yq`) may
be used from a debug container in the target cluster to provide a workspace.  
[source, shell]
----
oc debug --image=push quay.io/lglussen/ocp-tools:latest
> oc login oc login --token=${YOUR_TOKEN} --server=${YOUR_OCP_API}
----


== VM Namespace Migration in OpenShift (migrate.py)

Script to support cloning VMs into a new namespace as a workaround to no direct namespace migration feature.

It would be more efficient to reuse the same PV rather than cloning, but this method doesn't require anything destructive to the original VM setup (with the possible exception of MAC address if the MAC addresses need to Migrate). This makes it simple to revert to the old vm if problems are encountered bringing the VM online in the new namespace. Perhaps a direct method will be added later.

The scripts in the repository handle a few repetitive tasks but may not cover all usecases.
The _may_ work for all your vms - _please_ test.

.The scripts do the following:
1. configure namespace permissions to allow cloning data between namespaces
2. transform the source VM config into a new VM confg for the destination namespace
    * strips out state information and instance metadata (eg: uuid)
    * strips out Mac addresses (unless `--preserve-mac` is specified)
    * creates a DataVolume template to copy the PVC of the original VM
    * modifies the namespace

[source, shell]
----
./vm_migrate_namespace.py src_namespace dest_namespace --preserve-mac
----

The script generates YAML files for the new VMs in the new namespace.  Running `oc apply -f` against the files is all that 
is needed to start the process.

=== Reference Shell Script migration.sh
For reference, I have kept a copy of `migrate.sh` under `sh_example` which doesn't account for VMs with variable numbers of disk devices.
It is however fairly simple to read and illustrates the core set of operations succinctly. 
[source, shell]
----
cd sh_example
sh clone-permissions.sh <source namepsace> <destination namespace>
sh migrate.sh <vm_name> <src_namespace> <target_namespace>
----


== Striping Out Datavolume Configuration
Datavolumes are useful for preparing and importing data but are not really required once a VM is operational.
To replace Datavolume configuration with direct PVC configuration for a more lean and direct VM configuration file
you may run the `vm_datavolume_to_pvc.py` script

[source, shell]
----
vm_datavolume_to_pvc.py vm_name -n your-namespace --apply
----

Running with `--apply` will make the change to your system and delete the old Datavolume definitions. Running without
`--apply` will generate a yaml file that represents what we _want_ the vm to look like (datavolume replaced with PVC)
but doesn't apply any changes to the cluster.



