= Scripts for OpenShift Virtualization Operations

== Containerized ENV
While not required, this repository along with helpful tooling such as `yq` may
be run as a debug container in the target cluster to provide a workspace.
[source, shell]
----
oc debug --image=push quay.io/lglussen/ocp-tools:latest
> oc login oc login --token=${YOUR_TOKEN} --server=${YOUR_OCP_API}
----


== VM Namespace Migration in OpenShift (migrate.py)

Script to support cloning VMs into a new namespace as a workaround to no direct namespace migration feature.

It would be more efficient to reuse the same PV rather than cloning, but this method doesn't require anything destructive to the original VM setup (with the possible exception of MAC address if the MAC addresses need to Migrate). This makes it simple to revert to the old vm if problems are encountered bringing the VM online in the new namespace. Perhaps a direct method will be added later.

The scripts in the repository handle a few repetitive tasks but may not cover all usecases.
The _may_ work for all your vms - _please_ test.

.The scripts do the following:
1. configure namespace permissions to allow cloning data between namespaces
2. transform the source VM config into a new VM confg for the destination namespace
    * strips out state information and instance metadata (eg: uuid)
    * strips out Mac addresses (unless `--preserve-mac` is specified)
    * creates a DataVolume template to copy the PVC of the original VM
    * modifies the namespace

=== Reference Shell Script migration.sh
For reference, I have kept a copy of `migrate.sh` which doesen't account for VMs with variable numbers of disk devices.
It is however fairly simple to read and illustrates the core set of operations succinctly. 

== Configure Clone Permissions

To allow cloning VM volumes into destination namespace, permissions need to be
configured to allow access.
[source, shell]
----
sh lib/clone-permissions.sh <source namepsace> <destination namespace>
----

== Create the new VirtualMachine configuration

We can export and modify the source VM configuration to deploy in our new 
namespace.

[,shell]
----
# for a single vm
./transform.sh vm-name source-namespace destination-namespace

# for all vms in a namespace
for vm in `oc get vms -n source-ns -o custom-columns=NAME:.metadata.name --no-headers`; do
  ./transform.sh $vm source-ns destination-ns
done
----

.Output Directories:
****


source_vm/:: `<vm-name>.yaml` (export of the current vm configuration)
dest_vm/:: `new-<vm-name>.yaml` transformed yaml of the new VM definition 
****

WARNING: this will skip vms with more than one volume unless it is exactly 2 volumes of the pattern: one dataVolume and one CloudInitNoCloud volume. This script focuses on simple / common VMs and the output can be used as a guide for converting more complicated VMs


Lastly, you can run `oc apply -f new-<vm-name>.yaml` against the files in the `./dest_vm/` directory to create the new vm definitions. Be sure to power down the source namespace beforehand.


